#!/usr/bin/env bash
set -e

port=3999
script/server -p "$port" &>/dev/null &
pid=$!

trap "kill $pid" EXIT INT

while ! lsof -i :$port >/dev/null; do
  sleep .05
done

[ -z "$CI" ] || echo "PhantomJS $(phantomjs --version)"

phantomjs ./test/run-qunit.js \
  "http://localhost:$port/?jquery=3.2" \
  "http://localhost:$port/?jquery=2.2" \
  "http://localhost:$port/?jquery=1.12"
